tunnel: ee16304e-8951-40d6-9553-a4d08672d380
credentials-file: /root/.cloudflared/ee16304e-8951-40d6-9553-a4d08672d380.json

ingress:
  - hostname: iloura.co.kr
    service: http://localhost:4321
  - service: http_status:404
